Website v2
EuroHacks/website pull request #5
Opened 2024-10-20 12:55 UTC by Nikos1508

Use Astro instead of plain HTML-CSS. Create Eurohacks, About Us, and Home pages. Setting some of them as "coming soon" features and also working on other features and typos.

2024-10-20 13:04 UTC, BudzioT approved these changes

2024-10-20 13:08 UTC, ThomasJPrice approved these changes

2024-10-20 13:17 UTC, GalaxyGamingBoy approved these changes
LGTM!

2024-10-21 13:58 UTC, gicorada approved these changes

2024-10-27 09:57 UTC, v1ctorio requested changes

2024-10-27 10:02 UTC, Nikos1508 commented on src/components/Footer.astro
> +                            <td> greece@europehacks.com </td>
I will change it asap

2024-10-27 10:03 UTC, Nikos1508 commented on src/content/events/poland.json
> +            "translation": "For changin the language from English to Polish press this button:",
I will probably change that but it won't be shown anywhere so I don't think it is important for THIS update

2024-10-27 10:04 UTC, Nikos1508 commented on src/components/Footer.astro
> +                            <td> marios.mitsios@europehacks.org </td>
I can't understand what are you referring to here, sorry

2024-10-27 10:05 UTC, Nikos1508 commented on src/content/events/germany.json
> +            "translation": "For changin the language from German to English press this button:",
Same with the poland.json, I will change it but it's not that important for now so we could leave it as it is for now.

2024-10-27 10:06 UTC, v1ctorio commented on src/content/events/poland.json
> +            "translation": "For changin the language from English to Polish press this button:",
Ok

2024-10-27 10:07 UTC, v1ctorio commented on src/components/Footer.astro
> +                            <td> marios.mitsios@europehacks.org </td>
That's not the domain ><

2024-10-27 10:07 UTC, Nikos1508 commented on src/pages/index.astro
> +			answer=" Yes. It is a coding event, you have to get your devices (it could be a tablet or a laptop) so you can make your projects. We may be able to offer some laptop in 1 or 2 people but you have
Okay, yes, you are right. I made this FAQ without asking anyone. I will make a Google document so we can review FAQ questions before we launch our website. ❤️

2024-10-27 10:08 UTC, Nikos1508 commented on src/pages/index.astro
> +			answer=" Don’t hesitate to send us an email with all your question. We will answer them as soon as possible (probably under 24h). You can either send an email in questions@eurohacks.org or in your
Okay, we will review it on Google Document

2024-10-27 10:08 UTC, Nikos1508 commented on src/components/HackathonElement.astro
> +                <br> <i class="fa-solid fa-envelope mr-2 my-3"></i> Mail: {country}@eurohakcs.org
I will change it asap

2024-10-27 10:10 UTC, Nikos1508 commented on src/components/Footer.astro
> +                            <td> greece@europehacks.com </td>
Wait, I think that I have changed it. Press "edit file" and tell me if you can see the changes. idk why they are not shown here. I will try to fix it.

2024-10-27 10:19 UTC, v1ctorio approved these changes

2024-10-27 10:20 UTC, v1ctorio commented
Ready to merge!

2024-10-27 15:31 UTC, merged